services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./config/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config/grafana/config.monitoring
    depends_on:
      - prometheus
    network_mode: host
