services:
  mqtt:
    image: "eclipse-mosquitto:latest"
    network_mode: host
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
