{
 "title": "Metrics dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_api_total_active_connections{}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Total packets since restart",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_api_total_received_messages{}",
     "legendFormat": "Total received packets"
    },
    { "expr": "app_api_total_sent_messages{}", "legendFormat": "Total sent packets" }
   ]
  },
  {
   "title": "Total packets per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(app_api_total_received_messages{}[$__interval])",
     "legendFormat": "Total received packets per second"
    },
    {
     "expr": "rate(app_api_total_sent_messages{}[$__interval])",
     "legendFormat": "Total sent packets per second"
    }
   ]
  }
 ]
}